version: '3.6'
services:
  neo4j:
    image: neo4j
    environment: # to read more about env variables: https://neo4j.com/docs/operations-manual/current/installation/docker/
      - NEO4J_AUTH=none   #none for no passwor. use neo4j/<password> to provide password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes  # to accept the license agreement
      - NEO4J_HEAP_MEMORY=1024
      - NEO4J_CACHE_MEMORY=1G
      #to specify other settings related to clusters, please see: https://neo4j.com/docs/operations-manual/current/installation/docker/ . But clustering seems to be  available only for enterprise addition 
    volumes:
      - ${HOME}/neo4j/data:/data #for data storage. home:  /var/lib/neo4j, path:  /var/lib/neo4j/data
      #- ${HOME}/neo4j/logs:/logs #for logs. home:  /var/lib/neo4j, path:  /var/lib/neo4j/logs
      #- ${HOME}/neo4j/conf:/conf #for conf. home:  /var/lib/neo4j, path:  /var/lib/neo4j/conf
    
    ports: # to read more about neo4j ports: https://neo4j.com/docs/operations-manual/current/configuration/ports/
      - "7474:7474"  # for http
      - "7687:7687"  # for bolt
      - "7473:7473" # for https
    network_mode: "host"
  neo4j_service:
    image: muhammadimran/neo4j_service
    depends_on:
      - "neo4j"
    environment:
      - GRAPHDB_URI=${GRAPHDB_URI}
      - GRAPHDB_USER=${GRAPHDB_USER}
      - GRAPHDB_PASS=${GRAPHDB_PASS}
      - NEO4J_DATABASE_HOST=${NEO4J_DATABASE_HOST}
      - NEO4J_DATABASE_PORT=${NEO4J_DATABASE_PORT}
    network_mode: "host"
    #it may take longer for neo4j to run, so wait for it before starting this service
    #command: ["/wait-for-neo4j.sh", "x.x.x.x", "7687", "python3", "/openstack_neo4j_service/graph_service_resource/main.py"]
  openstack_querier:
    image: muhammadimran/openstack_querier
    depends_on:
      - "neo4j"
      - "neo4j_service"
    volumes:
      - ./ssh_keys:/user_keys   #since we are getting VMs for all users, so need to get more than one key file. the keys in ssh_keys should have the same name as user_name in openstack
      #- ./openstack_info.json:/openstack_info.json
    network_mode: "host"
    #it may take longer for the dependent component to run, so wait for it before starting this mediator
    #command: ["/wait-for-neo4j-service.sh", "x.x.x.x", "15135", "python3", "/openstack_neo4j_service/neo4jservice_os_mediator/main.py"]
    env_file:
      - .env
