version: '3.6'
services:
  neo4j:
    image: neo4j
    environment: # to read more about env variables: https://neo4j.com/docs/operations-manual/current/installation/docker/
      - NEO4J_AUTH=none   #none for no passwor. use neo4j/<password> to provide password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes  # to accept the license agreement
      - NEO4J_HEAP_MEMORY=1024
      - NEO4J_CACHE_MEMORY=1G
      #to specify other settings related to clusters, please see: https://neo4j.com/docs/operations-manual/current/installation/docker/ . But clustering seems to be  available only for enterprise addition 
    volumes:
      - ${HOME}/neo4j/data:/data #for data storage. home:  /var/lib/neo4j, path:  /var/lib/neo4j/data
      #- ${HOME}/neo4j/logs:/logs #for logs. home:  /var/lib/neo4j, path:  /var/lib/neo4j/logs
      #- ${HOME}/neo4j/conf:/conf #for conf. home:  /var/lib/neo4j, path:  /var/lib/neo4j/conf
    
    ports: # to read more about neo4j ports: https://neo4j.com/docs/operations-manual/current/configuration/ports/
      - "7474:7474"  # for http
      - "7687:7687"  # for bolt
      - "7473:7473" # for https
    network_mode: "host"
  neo4j_service:
    image: muhammadimran/neo4j_service
    depends_on:
      - "neo4j"
    environment:
      - GRAPHDB_URI=${GRAPHDB_URI}
      - GRAPHDB_USER=${GRAPHDB_USER}
      - GRAPHDB_PASS=${GRAPHDB_PASS}
      - NEO4J_DATABASE_HOST=${NEO4J_DATABASE_HOST}
      - NEO4J_DATABASE_PORT=${NEO4J_DATABASE_PORT}
      - LOGS_FILE_PATH=/cloud_reconnoiterer/logs/cloud_reconnoiterer.log
      - LOG_LEVEL=DEBUG
    network_mode: "host"
  openstack_querier:
    image: muhammadimran/openstack_querier
    depends_on:
      - "neo4j"
      - "neo4j_service"
    network_mode: "host"
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3-management #rabbitmq with management plugin
    environment:
      - RABBITMQ_NODENAME=none   
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=70%
      - RABBITMQ_ERLANG_COOKIE=
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=
      #env var for ulimit???
      #for more configurations, see https://hub.docker.com/_/rabbitmq/
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    network_mode: "host"
