version: '3.6'
services:
  rabbitmq:
    image: rabbitmq:3
    environment:
      - RABBITMQ_NODENAME=none   
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=70%
      - RABBITMQ_ERLANG_COOKIE=
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password  # later 'docker secrets' may be used for user and password instead of setting them as env variables
      - RABBITMQ_DEFAULT_VHOST=
      #env var for ulimit???
      #for more configurations, see https://hub.docker.com/_/rabbitmq/
    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    network_mode: "host"
  events_notifier:
    image: muhammadimran/docker-events-notifier # not published yet
    depends_on:
      - "rabbitmq"
    environment:
      - RABBITMQ_URL_DOCKER=${GRAPHDB_URI}
    deploy:
      mode: global #should run on each machine
    #network_mode: "host" # host mode may not be needed