version: '3.6'
services:
  neo4j:
    image: neo4j
    environment: # to read more about env variables: https://neo4j.com/docs/operations-manual/current/installation/docker/
      - NEO4J_AUTH=none   #none for no passwor. use neo4j/<password> to provide password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes  # to accept the license agreement
      - NEO4J_HEAP_MEMORY=1024
      - NEO4J_CACHE_MEMORY=1G
      #to specify other settings related to clusters, please see: https://neo4j.com/docs/operations-manual/current/installation/docker/ . But clustering seems to be  available only for enterprise addition 
    volumes:
      - ${HOME}/neo4j/data:/data #for data storage. home:  /var/lib/neo4j, path:  /var/lib/neo4j/data
      #- ${HOME}/neo4j/logs:/logs #for logs. home:  /var/lib/neo4j, path:  /var/lib/neo4j/logs
      #- ${HOME}/neo4j/conf:/conf #for conf. home:  /var/lib/neo4j, path:  /var/lib/neo4j/conf
    
    ports: # to read more about neo4j ports: https://neo4j.com/docs/operations-manual/current/configuration/ports/
      - "7474:7474"  # for http
      - "7687:7687"  # for bolt
      - "7473:7473" # for https
    network_mode: "host"
  neo4j_service:
    image: muhammadimran/openstack-neo4j-service
    environment:
      - GRAPHDB_URI=${GRAPHDB_URI}
      - GRAPHDB_USER=${GRAPHDB_USER}
      - GRAPHDB_PASS=${GRAPHDB_PASS}
    network_mode: "host"
  openstack_querier:
    image: muhammadimran/openstack-querier
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}  #env file doesn't support multiline string variable so far. private key is needed by python code to ssh VMs to get containers running inside those.
    #  - NEO4J_PYTHON_SERVICE=${NEO4J_PYTHON_SERVICE}
    #  - OS_PROJECT_DOMAIN_NAME=${OS_PROJECT_DOMAIN_NAME}
    #  - OS_USER_DOMAIN_NAME=${OS_USER_DOMAIN_NAME}
    #  - OS_PROJECT_NAME=${OS_PROJECT_NAME}
    #  - OS_USERNAME=${OS_USERNAME}
    #  - OS_PASSWORD=${OS_PASSWORD}
    #  - OS_AUTH_URL=${OS_AUTH_URL}
    #  - OS_IDENTITY_API_VERSION=${OS_IDENTITY_API_VERSION}
    #  - OS_IMAGE_API_VERSION=${OS_IMAGE_API_VERSION}
    network_mode: "host"
    env_file:
      - .env


