version: '3.6'
services:
  rabbitmq:
    image: rabbitmq:3-management #rabbitmq with management plugin
    environment:
      - RABBITMQ_NODENAME=none   
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=70%
      - RABBITMQ_ERLANG_COOKIE=
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password  # later 'docker secrets' may be used for user and password instead of setting them as env variables
      - RABBITMQ_DEFAULT_VHOST=
      #env var for ulimit???
      #for more configurations, see https://hub.docker.com/_/rabbitmq/
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    network_mode: "host"
  events_notifier:
    image: muhammadimran/docker_events_notifier:1.0
    depends_on:
      - "rabbitmq"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RABBITMQ_URL_DOCKER=${RABBITMQ_URL_DOCKER} # format:amqp://user:password@ip:5672
    deploy:
      mode: global #should run on each machine
    #network_mode: "host" # host mode may not be needed
