version: '3.6'
services:
  events_notifier:
    image: muhammadimran/docker_events_notifier:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_URL_DOCKER=${RABBITMQ_URL_DOCKER}
      - LOGS_FILE_PATH=/cloud_reconnoiterer/logs/cloud_reconnoiterer.log
      - LOG_LEVEL=DEBUG
    deploy:
      mode: global #should run on each machine
    #network_mode: "host" # host mode may not be needed
